dist: trusty
language: c
sudo: false
addons:
  apt:
    packages:
      - check
cache:
    apt: true
    ccache: true
    
env:
    global:
      - TRAVIS=1

script:
    - make test

after_success:
    - ccache --show-stats
