dist: trusty
language: c
sudo: false
addons:
  apt:
    packages:
      - check
cache:
    apt: true
    ccache: true

# Run PHPs run-tests.php 
script:
    - make test

after_success:
    - ccache --show-stats
